# Generated by Django 3.0.1 on 2019-12-26 18:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_analista', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Analista',
                'verbose_name_plural': 'Analistas',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=200)),
                ('local', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('titulo_chamado', models.CharField(max_length=100)),
                ('id_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_chamado', models.CharField(choices=[('INCIDENTE', 'Incidente'), ('REQUISICAO', 'Requsição')], default='Incidente', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('CONCLUIDO', 'Concluido')], default='Aberto', max_length=20)),
                ('descricao', models.TextField()),
                ('solucao', models.TextField(blank=True, null=True)),
                ('data_abertura', models.DateField(default=django.utils.timezone.now)),
                ('data_alteracao', models.DateField(default=django.utils.timezone.now)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='chamado.Analista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='chamado.Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.Equipamento')),
            ],
        ),
    ]
