# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_chamado', models.CharField(choices=[(b'INCIDENTE', b'Incidente'), (b'REQUISICAO', b'Requsicao')], max_length=20)),
                ('status', models.CharField(choices=[(b'ABERTO', b'Aberto'), (b'EM_ANDAMENTO', b'Em andamento'), (b'AGUARDANDO', b'Aguardando'), (b'CONCLUIDO', b'Concluido')], default=b'Aberto', max_length=20)),
                ('descricao', models.TextField()),
                ('solucao', models.TextField()),
                ('data_abertura', models.DateField(auto_now=True)),
                ('analista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamado.Analista')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=200)),
                ('local', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamado.Cliente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.Equipamento'),
        ),
    ]
