# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.CharField(choices=[(b'INCIDENTE', b'Incidente'), (b'REQUISICAO', b'Requsi\xc3\xa7\xc3\xa3o')], max_length=20),
        ),
    ]
