# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-23 20:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamado', '0002_auto_20191223_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analista',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='analista',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='analista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='analista',
            name='id',
        ),
        migrations.RemoveField(
            model_name='analista',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='analista',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.AddField(
            model_name='analista',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.CharField(choices=[(b'INCIDENTE', b'Incidente'), (b'REQUISICAO', b'Requsi\xc3\xa7\xc3\xa3o')], default=b'Incidente', max_length=20),
        ),
    ]
