# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-24 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_auto_20191223_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analista',
            options={'verbose_name': 'Analista', 'verbose_name_plural': 'Analistas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
