# Generated by Django 3.0.1 on 2019-12-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0005_auto_20191224_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='titulo_chamado',
            field=models.CharField(default='tutulo', max_length=100),
            preserve_default=False,
        ),
    ]
