# Generated by Django 3.0.1 on 2019-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0006_chamado_titulo_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_ateracao',
            field=models.DateField(auto_now=True),
        ),
    ]
