# Generated by Django 3.0.1 on 2019-12-26 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0007_chamado_data_ateracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_ateracao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
