# Generated by Django 3.0.1 on 2019-12-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0008_auto_20191226_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='data_ateracao',
            new_name='data_alteracao',
        ),
    ]
